// Mocks generated by Mockito 5.4.4 from annotations
// in restaurant_booking_app/test/presentation/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_booking_app/core/network/api_result.dart' as _i2;
import 'package:restaurant_booking_app/domain/entities/auth.dart' as _i5;
import 'package:restaurant_booking_app/domain/entities/user.dart' as _i11;
import 'package:restaurant_booking_app/domain/usecases/auth/get_current_user_usecase.dart'
    as _i10;
import 'package:restaurant_booking_app/domain/usecases/auth/login_with_email_usecase.dart'
    as _i6;
import 'package:restaurant_booking_app/domain/usecases/auth/login_with_phone_usecase.dart'
    as _i3;
import 'package:restaurant_booking_app/domain/usecases/auth/login_with_social_usecase.dart'
    as _i7;
import 'package:restaurant_booking_app/domain/usecases/auth/logout_usecase.dart'
    as _i8;
import 'package:restaurant_booking_app/domain/usecases/auth/refresh_token_usecase.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginWithPhoneUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithPhoneUseCase extends _i1.Mock
    implements _i3.LoginWithPhoneUseCase {
  MockLoginWithPhoneUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<void>> sendSmsCode(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSmsCode,
          [phone],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #sendSmsCode,
            [phone],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> verifyOtp(
    String? phone,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [
            phone,
            code,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #verifyOtp,
            [
              phone,
              code,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);
}

/// A class which mocks [LoginWithEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithEmailUseCase extends _i1.Mock
    implements _i6.LoginWithEmailUseCase {
  MockLoginWithEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> execute(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #execute,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);
}

/// A class which mocks [LoginWithSocialUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginWithSocialUseCase extends _i1.Mock
    implements _i7.LoginWithSocialUseCase {
  MockLoginWithSocialUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> execute(
    String? token,
    _i5.SocialProvider? provider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            token,
            provider,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #execute,
            [
              token,
              provider,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i8.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<void>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);
}

/// A class which mocks [RefreshTokenUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshTokenUseCase extends _i1.Mock
    implements _i9.RefreshTokenUseCase {
  MockRefreshTokenUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> execute(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [refreshToken],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #execute,
            [refreshToken],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i10.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i11.User?>> execute() => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i11.User?>>.value(
            _FakeApiResult_0<_i11.User?>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i11.User?>>);
}
