// Mocks generated by Mockito 5.4.4 from annotations
// in restaurant_booking_app/test/domain/usecases/auth/login_with_phone_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:restaurant_booking_app/core/network/api_result.dart' as _i2;
import 'package:restaurant_booking_app/domain/entities/auth.dart' as _i5;
import 'package:restaurant_booking_app/domain/entities/user.dart' as _i6;
import 'package:restaurant_booking_app/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AuthState> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i5.AuthState>.empty(),
      ) as _i4.Stream<_i5.AuthState>);

  @override
  _i4.Future<_i2.ApiResult<void>> sendSmsCode(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSmsCode,
          [phone],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #sendSmsCode,
            [phone],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> verifyOtp(
    String? phone,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [
            phone,
            code,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #verifyOtp,
            [
              phone,
              code,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> loginWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithEmail,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #loginWithEmail,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> loginWithSocial(
    String? token,
    _i5.SocialProvider? provider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithSocial,
          [
            token,
            provider,
          ],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #loginWithSocial,
            [
              token,
              provider,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.AuthResult>> refreshToken(
          String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [refreshToken],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i5.AuthResult>>.value(
            _FakeApiResult_0<_i5.AuthResult>(
          this,
          Invocation.method(
            #refreshToken,
            [refreshToken],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i5.AuthResult>>);

  @override
  _i4.Future<_i2.ApiResult<void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);

  @override
  _i4.Future<_i2.ApiResult<_i6.User?>> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i6.User?>>.value(
            _FakeApiResult_0<_i6.User?>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i6.User?>>);

  @override
  _i4.Future<_i2.ApiResult<_i6.User>> updateProfile(_i6.User? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [user],
        ),
        returnValue: _i4.Future<_i2.ApiResult<_i6.User>>.value(
            _FakeApiResult_0<_i6.User>(
          this,
          Invocation.method(
            #updateProfile,
            [user],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<_i6.User>>);

  @override
  _i4.Future<_i2.ApiResult<void>> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #deleteAccount,
            [],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);

  @override
  _i4.Future<_i2.ApiResult<void>> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestPasswordReset,
          [email],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #requestPasswordReset,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);

  @override
  _i4.Future<_i2.ApiResult<void>> resetPassword(
    String? token,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [
            token,
            newPassword,
          ],
        ),
        returnValue:
            _i4.Future<_i2.ApiResult<void>>.value(_FakeApiResult_0<void>(
          this,
          Invocation.method(
            #resetPassword,
            [
              token,
              newPassword,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ApiResult<void>>);
}
